##########################################
########## Xiaomi Drivers ###############
##########################################

obj-$(CONFIG_XIAOMI_HW_VERSION) += hw_version/
obj-$(CONFIG_XIAOMI_NOTIFIER)   += mi_notifier/
