dtb-y += $(subst ",,$(CONFIG_MSTAR_CHIP_NAME)_an).dtb
dtb-y += $(subst ",,$(CONFIG_MSTAR_CHIP_NAME)_ramdisk).dtb

dtb-$(CONFIG_MSTAR_M7322) += m7322_an_midgard.dtb
dtb-$(CONFIG_MSTAR_M7322) += m7322_an_avb.dtb
dtb-$(CONFIG_MSTAR_M7322) += m7322_an.main_dtb
dtb-$(CONFIG_MSTAR_M7322) += m7322_overlay_1.dtbo
dtb-$(CONFIG_MSTAR_M7322) += m7322_overlay_28.dtbo
dtb-$(CONFIG_MSTAR_M7322) += m7322_overlay_avb28.dtbo

dtb-$(CONFIG_MSTAR_M7632) += \
	m7632_an_avb.dtb \
	m7632_an.main_dtb \
	m7632_an_midgard.dtb \
	m7632_overlay_28.dtbo \
	m7632_overlay_avb28.dtbo \
	m7632_MediaTek_m7632_MTV19006.dtb \
	m7632_MediaTek_m7632_MTV19008.dtb \
	m7632_MediaTek_m7632_MT164B.dtb

dtb-$(CONFIG_MSTAR_M7332) += \
	m7332_an_avb.dtb \
	m7332_an.main_dtb \
	m7332_overlay.dtbo \
	m7332_overlay_28.dtbo \
	m7332_overlay_dp_28.dtbo \
	m7332_overlay_avb28.dtbo \
	m7332_overlay_dp_avb28.dtbo \
	m7332_MediaTek_m7332_MT165B.dtb \
	m7332_MediaTek_m7332_MT168B.dtb \
	m7332_MediaTek_m7332_MT168B_20AT.dtb \
	m7332_MediaTek_m7332_MT169B-2K.dtb \
	m7332_MediaTek_m7332_MT169B-4K.dtb \
	m7332_MediaTek_m7332_MTV19007.dtb \
	m7332_MediaTek_m7332_MTV19013.dtb \
	m7332_MediaTek_m7332_MT165B_avb.dtb \
	m7332_MediaTek_m7332_MT165B_overlay.dtbo \
	m7332_MediaTek_m7332_MT165B_overlay_28.dtbo \
	m7332_MediaTek_m7332_MT165B_overlay_avb28.dtbo \
	m7332_MediaTek_m7332_MT165B_overlay_avb.dtbo \
	m7332_MediaTek_m7332_MT165B_overlay_dp_28.dtbo \
	m7332_MediaTek_m7332_MT165B_overlay_dp_avb28.dtbo \
	m7332_MediaTek_m7332_MT165B_10AT_overlay_dp_avb28.dtbo \
	m7332_MediaTek_m7332_MT165B_overlay_dp.dtbo \
	m7332_MediaTek_m7332_MT168B_avb.dtb \
	m7332_MediaTek_m7332_MT168B_20AT_avb.dtb \
	m7332_MediaTek_m7332_MT168B_overlay.dtbo \
	m7332_MediaTek_m7332_MT168B_20AT_overlay.dtbo \
	m7332_MediaTek_m7332_MT168B_overlay_28.dtbo \
	m7332_MediaTek_m7332_MT168B_20AT_overlay_28.dtbo \
	m7332_MediaTek_m7332_MT168B_overlay_avb28.dtbo \
	m7332_MediaTek_m7332_MT168B_20AT_overlay_avb28.dtbo \
	m7332_MediaTek_m7332_MT168B_overlay_avb.dtbo \
	m7332_MediaTek_m7332_MT168B_20AT_overlay_avb.dtbo \
	m7332_MediaTek_m7332_MT168B_overlay_dp_28.dtbo \
	m7332_MediaTek_m7332_MT168B_20AT_overlay_dp_28.dtbo \
	m7332_MediaTek_m7332_MT168B_overlay_dp_avb28.dtbo \
	m7332_HKC_HKC_4K_ATV_SA_MT168B_20AT_overlay_dp_avb28.dtbo \
	m7332_HKC_HKC_4K_ATV_PA_MT168B_20AT_overlay_dp_avb28.dtbo \
	m7332_HKC_HKC_4K_ATV_US_MT168B_20AT_overlay_dp_avb28.dtbo \
	m7332_MediaTek_m7332_MT168B_20AT_overlay_dp_avb28.dtbo \
	m7332_expressluck_Caixun_4K_ATV2_MT168B_20AT_overlay_dp_avb28.dtbo \
	m7332_expressluck_SMARTTECH_UHD_ATV_MT168B_20AT_overlay_dp_avb28.dtbo \
	m7332_MediaTek_m7332_MT168B_overlay_dp.dtbo \
	m7332_MediaTek_m7332_MT168B_20AT_overlay_dp.dtbo \
	m7332_MediaTek_m7332_MT165B_overlay_28_ledblink.dtbo \
	m7332_MediaTek_m7332_MT165B_overlay_avb28_ledblink.dtbo \
	m7332_MediaTek_m7332_MT165B_overlay_avb_ledblink.dtbo \
	m7332_MediaTek_m7332_MT165B_overlay_dp_28_ledblink.dtbo \
	m7332_MediaTek_m7332_MT165B_overlay_dp_avb28_ledblink.dtbo \
	m7332_MediaTek_m7332_MT165B_overlay_dp_ledblink.dtbo \
	m7332_MediaTek_m7332_MT165B_overlay_ledblink.dtbo \
	m7332_MediaTek_m7332_MT168B_overlay_28_ledblink.dtbo \
	m7332_MediaTek_m7332_MT168B_20AT_overlay_28_ledblink.dtbo \
	m7332_MediaTek_m7332_MT168B_overlay_avb28_ledblink.dtbo \
	m7332_MediaTek_m7332_MT168B_20AT_overlay_avb28_ledblink.dtbo \
	m7332_MediaTek_m7332_MT168B_overlay_avb_ledblink.dtbo \
	m7332_MediaTek_m7332_MT168B_20AT_overlay_avb_ledblink.dtbo \
	m7332_MediaTek_m7332_MT168B_overlay_dp_28_ledblink.dtbo \
	m7332_MediaTek_m7332_MT168B_20AT_overlay_dp_28_ledblink.dtbo \
	m7332_MediaTek_m7332_MT168B_overlay_dp_avb28_ledblink.dtbo \
	m7332_MediaTek_m7332_MT168B_20AT_overlay_dp_avb28_ledblink.dtbo \
	m7332_MediaTek_m7332_MT168B_overlay_dp_ledblink.dtbo \
	m7332_MediaTek_m7332_MT168B_20AT_overlay_dp_ledblink.dtbo \
	m7332_MediaTek_m7332_MT168B_overlay_ledblink.dtbo \
	m7332_MediaTek_m7332_MT168B_20AT_overlay_ledblink.dtbo \
	m7332_overlay_28_ledblink.dtbo \
	m7332_overlay_avb28_ledblink.dtbo \
	m7332_overlay_dp_28_ledblink.dtbo \
	m7332_overlay_dp_avb28_ledblink.dtbo \
	m7332_overlay_ledblink.dtbo \
	m7332_funai_m7332_MT168B_20AT_overlay_dp_avb28.dtbo \
	m7332_Philips_m7332_MT168B_20AT_overlay_dp_avb28.dtbo \
	m7332_mtc_m7332_MT168B_20AT_overlay_dp_avb28.dtbo
	
dtb-$(CONFIG_MSTAR_M7642) += \
	m7642_MediaTek_m7642_MTV19020.dtb \
	m7642_MediaTek_m7642_MTV19024.dtb \
	m7642_MediaTek_m7642_MT166B.dtb \
	m7642_an_avb.dtb \
	m7642_an.main_dtb \
	m7642_overlay_28.dtbo \
	m7642_overlay_dp_28.dtbo \
	m7642_overlay_avb28.dtbo \
	m7642_overlay_dp_avb28.dtbo \
	m7642_an_midgard.dtb \
        m7642_MediaTek_m7642_MT166B_overlay_dp_28.dtbo \
        m7642_MediaTek_m7642_MT166B_overlay_dp_avb28.dtbo \
        m7642_MediaTek_m7642_MT166B_avb.dtb \

dtb-$(CONFIG_MSTAR_MT5862) += \
	mt5862_an_avb.dtb \
	mt5862_an.main_dtb \
	mt5862_overlay_28.dtbo \
	mt5862_overlay_avb28.dtbo

dtb-$(CONFIG_MSTAR_MT5867) += \
	mt5867_MediaTek_mt5867_MT5867-M1V1-B2.dtb \
	mt5867_MediaTek_mt5867_MT5867-M2V1-N2.dtb \
	mt5867_MediaTek_mt5867_MT5867-H1V1-B2.dtb \
	mt5867_MediaTek_mt5867_MT5867-H2V1-N2.dtb

dtb-$(CONFIG_MSTAR_MT5889) += \
	m7642_MediaTek_m7642_MTV19020.dtb \
	mt5889_MediaTek_mt5889_MT5889-H1V1-B2-S.dtb \
	mt5889_MediaTek_mt5889_MT5889-H2V1-B4-S.dtb \
	mt5889_MediaTek_mt5889_MT5889-H2V1-B4-S_avb.dtb \
	mt5889_an_avb.dtb \
	mt5889_an.main_dtb \
	mt5889_overlay_dp_avb28.dtbo \
	mt5889_MediaTek_mt5889_MT5889-H2V1-B4-S_overlay_dp_28_ledblink.dtbo \
	mt5889_MediaTek_mt5889_MT5889-H2V1-B4-S_overlay_dp_avb28.dtbo \
	mt5889_MediaTek_mt5889_MT5889-H2V1-B4-S_overlay_dp_avb28_ledblink.dtbo \
	mt5889_MediaTek_mt5889_MT5889-H2V1-B4-S_overlay_dp_ledblink.dtbo \
	mt5889_overlay_avb28.dtbo \
	mt5889_overlay_module_dvfs_0.dtbo \
	mt5889_overlay_module_dvfs_1.dtbo

dtb-$(CONFIG_MSTAR_MT5872) += \
	mt5872_MediaTek_mt5872_MT5872-H1V1-B2-S.dtb \
	mt5872_MediaTek_mt5872_MT5872-H2V1-B2-S.dtb \
	mt5872_MediaTek_mt5872_MT5872-M1V1-B2.dtb \
	mt5872_MediaTek_mt5872_MT5872-M2V1-B2.dtb

